name = "TTE"
author = "TTE"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b80b569925bafa4f1adb13faaf625c6fcdb8bd698ffe1f24382810e99adbe91"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"
