name = "TTE"
author = "TTE"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a6531c37b29bc6c8d278f06790aeb80cdbf94c93b91dd2b503e4a363f322369"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"
